### ISSUE TITLE
Do you really use MPC?

### ISSUE THREAD

**Issue by TheSunWillRise** [yjw1029/Efficient-FedRec#1]
As privacy is one of the main concerns in your paper, I would expect to see your implementation in the codes but I don't find any part about MPC in the codes after checking the codes several times.
So, do you really use MPC in your experiments? If not, how do you conduct your experiments?

**Comment by yjw1029** [comment]
Hi, @TheSunWillRise. The MPC part is not included in the current code because of the experiment speed. Since secure aggregation only provides a privacy guarantee for communicating news representations and gradients, the output model and communication cost are the same as the implementation with Secure Aggregation.

We have implemented the Secure Aggregation to validate the correctness and the speed (Figure 4(d)). That part of the code will be cleaned and released ASAP.

**Comment by yjw1029** [comment]
The code with MPC is released in w-mpc branch.

**Comment by qwqwqwqw1** [comment]
The code with MPC is released in w-mpc branch. May I ask where is the w-mpc branch ? I cannot find it. Could you please help me?

**Comment by yjw1029** [comment]
Please refer to [here](https://github.com/yjw1029/Efficient-FedRec/tree/w-mpc)

**Comment by qwqwqwqw1** [comment]
Thank you so much for your reply and help!
